// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sharing-vision/database/ent/posts"
	"sharing-vision/database/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postsMixin := schema.Posts{}.Mixin()
	postsMixinFields0 := postsMixin[0].Fields()
	_ = postsMixinFields0
	postsFields := schema.Posts{}.Fields()
	_ = postsFields
	// postsDescCreatedAt is the schema descriptor for created_at field.
	postsDescCreatedAt := postsMixinFields0[0].Descriptor()
	// posts.DefaultCreatedAt holds the default value on creation for the created_at field.
	posts.DefaultCreatedAt = postsDescCreatedAt.Default.(func() time.Time)
	// postsDescUpdatedAt is the schema descriptor for updated_at field.
	postsDescUpdatedAt := postsMixinFields0[1].Descriptor()
	// posts.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	posts.DefaultUpdatedAt = postsDescUpdatedAt.Default.(func() time.Time)
	// posts.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	posts.UpdateDefaultUpdatedAt = postsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postsDescTitle is the schema descriptor for title field.
	postsDescTitle := postsFields[1].Descriptor()
	// posts.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	posts.TitleValidator = postsDescTitle.Validators[0].(func(string) error)
	// postsDescCategory is the schema descriptor for category field.
	postsDescCategory := postsFields[3].Descriptor()
	// posts.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	posts.CategoryValidator = postsDescCategory.Validators[0].(func(string) error)
	// postsDescID is the schema descriptor for id field.
	postsDescID := postsFields[0].Descriptor()
	// posts.DefaultID holds the default value on creation for the id field.
	posts.DefaultID = postsDescID.Default.(func() int)
}
